import { COLORS } from "./colorPalette";

// Compact catalog shapes as generated by scripts/generate-local-catalog.ts
export interface CatalogColor {
  name: string;
  hex: string;
}

export interface CatalogSetPart {
  p: string; // part_num
  c: number; // color_id
  r: number; // rarity_score
  i: string | null; // image_url
  nm?: string | null; // part name
}

export interface CatalogSetIndexEntry {
  n: string; // name
  y: number; // year
  t: number; // total_parts
  i: string | null; // image_url
  d: number; // diagnostic_rarity_sum
  c: Record<number, number>; // color profile (color_id -> percentage 0..100)
}

export interface CatalogPartInfo {
  r: number; // max rarity of the base part
  s: string[]; // set numbers containing the base part
}

// Reactive color table: templates calling resolveColor() re-render automatically
// once the catalog colors arrive — no manual {#key} re-mount needed.
let colors = $state<Record<number, CatalogColor> | null>(null);

let setsIndexCache: Record<string, CatalogSetIndexEntry> | null = null;
let partsCache: Record<string, CatalogPartInfo> | null = null;

let colorsLoadPromise: Promise<Record<number, CatalogColor>> | null = null;
let indexLoadPromise: Promise<{ sets: Record<string, CatalogSetIndexEntry>; parts: Record<string, CatalogPartInfo> }> | null = null;
const setPartsShardCache = new Map<string, Record<string, CatalogSetPart[]>>();
const setPartsShardPromises = new Map<string, Promise<Record<string, CatalogSetPart[]>>>();

export function clearCatalogCache() {
  colors = null;
  setsIndexCache = null;
  partsCache = null;
  colorsLoadPromise = null;
  indexLoadPromise = null;
  setPartsShardCache.clear();
  setPartsShardPromises.clear();
}

export function isCatalogReady(): boolean {
  return colors !== null;
}

// Load colors separately so the camera color analyzer is not blocked by the
// (much larger) sets/parts downloads.
export function loadColors(): Promise<Record<number, CatalogColor>> {
  if (colorsLoadPromise) return colorsLoadPromise;

  colorsLoadPromise = (async () => {
    try {
      const res = await fetch("/catalog/colors.json");
      if (!res.ok) throw new Error("Failed to load colors.json");
      colors = await res.json();
      return colors!;
    } catch (err) {
      console.warn("Using fallback COLORS", err);
      colors = COLORS;
      return COLORS;
    }
  })();

  return colorsLoadPromise;
}

// Load the lightweight matching data (set index + base-part index).
// A failed load resets the cached promise so a later call can retry.
export function loadCatalogIndex(): Promise<{ sets: Record<string, CatalogSetIndexEntry>; parts: Record<string, CatalogPartInfo> }> {
  if (indexLoadPromise) return indexLoadPromise;

  indexLoadPromise = (async () => {
    const colorsPromise = loadColors();

    const [setsRes, partsRes] = await Promise.all([
      fetch("/catalog/sets-index.json"),
      fetch("/catalog/parts.json")
    ]);

    if (!setsRes.ok || !partsRes.ok) {
      throw new Error("Failed to load sets-index or parts JSON files");
    }

    const [sets, parts] = await Promise.all([setsRes.json(), partsRes.json()]);
    await colorsPromise;

    setsIndexCache = sets;
    partsCache = parts;

    return { sets: setsIndexCache!, parts: partsCache! };
  })();

  indexLoadPromise.catch(() => {
    indexLoadPromise = null;
  });

  return indexLoadPromise;
}

// Load the catalog metadata (database version etc., REQ-START-002).
// Returns null when unavailable — callers keep their fallback label.
export async function loadCatalogMeta(): Promise<{ version: string } | null> {
  try {
    const res = await fetch("/catalog/meta.json");
    if (!res.ok) return null;
    const meta = await res.json();
    return typeof meta?.version === "string" ? meta : null;
  } catch {
    return null;
  }
}

// Shard key must mirror scripts/generate-local-catalog.ts (shardKeyForSet).
export function shardKeyForSet(setNum: string): string {
  const normalized = setNum.toLowerCase().replace(/[^a-z0-9]/g, "");
  return normalized.slice(0, 2) || "misc";
}

// Lazily load the diagnostic part list of a single set from its shard file.
// A failed load resets the shard promise so a later call can retry.
export function loadSetParts(setNum: string): Promise<CatalogSetPart[]> {
  const shard = shardKeyForSet(setNum);

  const cached = setPartsShardCache.get(shard);
  if (cached) return Promise.resolve(cached[setNum] || []);

  let shardPromise = setPartsShardPromises.get(shard);
  if (!shardPromise) {
    shardPromise = (async () => {
      const res = await fetch(`/catalog/set-parts/${shard}.json`);
      if (!res.ok) {
        throw new Error(`Failed to load set-parts shard ${shard}`);
      }
      const data = await res.json();
      setPartsShardCache.set(shard, data);
      return data as Record<string, CatalogSetPart[]>;
    })();
    shardPromise.catch(() => {
      setPartsShardPromises.delete(shard);
    });
    setPartsShardPromises.set(shard, shardPromise);
  }

  return shardPromise.then((data) => data[setNum] || []);
}

// Resolve a part's real English catalogue name (REQ-RAD-006: never the raw ID as name).
// Falls back to "Part <id>" only if the catalog lacks a name (e.g. pre-regeneration data).
export function resolvePartName(part: { p: string; nm?: string | null }): string {
  return part.nm && part.nm.trim() ? part.nm.trim() : `Part ${part.p}`;
}

// Resolve color details from the reactive catalog colors or the built-in fallback.
export function resolveColor(colorId: number): { id: number; name: string; hex: string } {
  const source = colors ?? COLORS;
  const entry = source[colorId] ?? COLORS[colorId];
  return entry
    ? { id: colorId, name: entry.name, hex: entry.hex }
    : { id: colorId, name: "Unknown", hex: "#777777" };
}
